<?php

namespace Servebolt\Optimizer\CronControl\Cronjobs;

use Servebolt\Optimizer\Traits\Singleton;

if (!defined('ABSPATH')) exit; // Exit if accessed directly

abstract class AbstractCommand
{
    use Singleton;

    /**
     * @var string Template used when generating cronjob comment.
     */
    private static $commentTemplate = 'Generated by Servebolt Optimizer (name=%s,rev=%s)';

    /**
     * Generate the comment that will be passed as meta data for the cronjob. This is later used for identification.
     *
     * @return string
     */
    public static function generateComment(): string
    {
        return sprintf(
            self::$commentTemplate,
            static::$commandName,
            static::$commandRevision
        );
    }
}
