<?php

namespace Unit;

use Servebolt\Optimizer\CronControl\Cronjobs\WpCliEventRun;
use Unit\Traits\EnvFile\EnvFileReaderTrait;
use ServeboltWPUnitTestCase;

class CronControlTest extends ServeboltWPUnitTestCase
{
    use EnvFileReaderTrait;

    public function testThatWeCanGenerateWpCronEventRunCommand()
    {
        self::getEnvFileReader();
        $command = 'wp cron event run --due-now --path=/kunder/serveb_123456/optimi_56789/public --quiet';
        $comment = 'Generated by Servebolt Optimizer (name=wp-cron-single-site,rev=1)';
        $interval = '*/10 * * * *';
        $this->assertEquals('wp-cron-single-site', WpCliEventRun::$commandName);
        $this->assertEquals('1', WpCliEventRun::$commandRevision);
        $this->assertEquals($command, WpCliEventRun::generateCommand());
        $this->assertEquals($comment, WpCliEventRun::generateComment());
        $this->assertEquals($interval, WpCliEventRun::getInterval());
        $this->assertEquals($interval . ' ' . $command, WpCliEventRun::generateCronjob(false));
        $this->assertEquals($interval . ' ' . $command . ' ' . $comment, WpCliEventRun::generateCronjob());
    }
}
